### ISSUE TITLE
ROK closes my devices

### ISSUE THREAD

**Issue by lapsap** [GabrielAgrela/ROKBOT#2]
Hi, im using bluestacks and windows 10.

when i use "adb device" without any app on or in another game, "adb devices" works fine.
but when i use it when i on ROK, the device is either offline or missing.
thus causing me to no be able to send any command to bluestacks.

does anyone have this problem too?
do you know how to fix this.

thanks

**Comment by russianguyx** [comment]
I have the same issue, after executing the command adb devices, sometimes it shows offile, other times no devices.

**Comment by GabrielAgrela** [comment]
Hey,

I've updates both the game and BlueStacks and it seems to disconnect the device (no device attached error) only when I open the game.

Not sure if it's some kind of anticheat measure or bug, but I tried it on my Android and it works fine.

Anyways, my solution was changing emulator, I'm now using MEmu and it works fine.

**Comment by russianguyx** [comment]
I just made the switch to MEmu, still the same error. Now the devices dont even appear. Is it the same ports?

**Comment by lapsap** [comment]
i also tried multiple emulators (even china ones), i think rise of kingdoms kills adb

**Comment by GabrielAgrela** [comment]
Yeah, its the same ports, but in MEmu we need to change the 127.0.0.1 to localhost. I uploaded the code to github.

About the rok killing adb, it's weird that it works on other emulators and android but it stopped working only in rok, and only in the newer versions of bluestacks, so im not sure thats a feature.

**Comment by GabrielAgrela** [comment]
If any of you try MEmu, let me know if you were able to go through the captcha verification manually. Mine just shows a white square.

**Comment by russianguyx** [comment]
Memu is known to have that for captcha. Unfortunately the only way to fix that is to create a new instance and cross your fingers that it fixes it. Main reason I switched to bluestacks is because of the captcha and random crashes with RoK. All other games seem to be fine.

I updates the files, will try to see if it works with the new code.

**Comment by russianguyx** [comment]
I have run with the new code and still having issues with my adb connecting to the locahost.

C:\Users\rachi\Desktop\RoK\ROKBOT-master>adb kill-server

C:\Users\rachi\Desktop\RoK\ROKBOT-master>adb connect localhost:21503
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
unable to connect to localhost:21503:21503

C:\Users\rachi\Desktop\RoK\ROKBOT-master>python rok.py

no device attached

C:\Users\rachi\Desktop\RoK\ROKBOT-master>PAUSE
Press any key to continue . . .
------------------------------------------------------------------------------------------------
and when I check the adb devices:

Microsoft Windows [Version 10.0.19041.450]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\rachi>adb devices
List of devices attached
emulator-5584   device

**Comment by lapsap** [comment]
Memu and adb now works for me, i can manually swipe through powershell

**Comment by russianguyx** [comment]
Not sure what I am doing wrong, I tried troubleshooting everything it seems. My adb just doesn't show any devices when I start RoK. I am using the newest Memu.

**Comment by GabrielAgrela** [comment]
Hey @russianguyx , i've ran into problems trying to connect to the MEmu with adb when i use the 5.1 android version of the emulator. 7.1 doesnt have any problem with the adb stuff, but it doesn't show the captcha, where the 5.1 version shows the captcha, but the adb doesn't work.

**Comment by GabrielAgrela** [comment]
@lapsap are you using MEmu with android 7?
If your captcha is working, ill try to create another instance of the same android version.

**Comment by russianguyx** [comment]
I had to modify the port, since the instance was using a different one. (I run many accounts sometimes and each instance veries in ports). I finally got it to work, however the bot is all wonky. I dont think it recognized my 1920x1080 with 320dpi.

It basically clicks the wrong buildings.

**Comment by sch33n** [comment]
is there any update on this?

I tried with Nox Player and Bluestacks. Both Disconnect at the end of the loading screen of ROK

\adb.exe devices
List of devices attached
127.0.0.1:5645  offline


My questions would be, iif should MeMu give  a try

**Comment by GabrielAgrela** [comment]
> is there any update on this?
> 
> I tried with Nox Player and Bluestacks. Both Disconnect at the end of the loading screen of ROK
> 
> \adb.exe devices
> List of devices attached
> 127.0.0.1:5645 offline
> 
> My questions would be, iif should MeMu give a try

I've been using MEmu since i have run into adb connection problems with the other ones.
