### ISSUE TITLE
Nothing happens in the game

### ISSUE THREAD

**Issue by Re4ll** [GabrielAgrela/ROKBOT#3]
Hello, I followed everything from the readme.

Now when I click on rok.bat it happens this here.

"
C:\Users\dare4\Desktop\rok>"C:\Users\dare4\Desktop\platform-tools\adb.exe" kill-server

C:\Users\dare4\Desktop\rok>"C:\Users\dare4\Desktop\platform-tools\adb.exe" connect localhost:21503
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to localhost:21503

C:\Users\dare4\Desktop\rok>cd C:\Users\dare4\Desktop\rok

C:\Users\dare4\Desktop\rok>python rok.py

C:\Users\dare4\Desktop\rok>PAUSE
Drücken Sie eine beliebige Taste . . .
"

but nothing happens in the game. do I have to do something else?

**Comment by GabrielAgrela** [comment]
That's weird.
Have you tried running the script only?
