### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by YoManWatSup** [GabrielAgrela/ROKBOT#4]
i just dont know what to do, please make a video about how to install it clearer

**Comment by Spooktr235** [comment]
it would be great to know how to really use

**Comment by dnndii132** [comment]
looks a nice bot but have no clue how to install/use it..

**Comment by GabrielAgrela** [comment]
I'll try making a video on how to setup the bot soon, but chances are that if you don't know how to set it up through the README, you wont know how to use it.

**Comment by dnndii132** [comment]
would love to see an tutorial video how to install the bot from strach..  hope to see it soon

**Comment by dnndii132** [comment]
any news about a video tutorial?

**Comment by GabrielAgrela** [comment]
https://youtu.be/8QPfjsv73X8
Let me know if this is clear enough.

**Comment by Spooktr235** [comment]
or something is not right or my python is always beeping and does not do the actions as it should be! Do you know what can be
